name: CI

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./docusaurus-cms

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: latest
                  run_install: false

            - name: Install dependencies
              run: pnpm install

            - name: Type check
              run: pnpm run typecheck

            - name: Format check
              run: pnpm run format:check

            # - name: Lint
            #   run: pnpm run lint

            - name: Run tests
              run: pnpm run test

            - name: Build
              run: pnpm run build
