name: CI

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Type check
              working-directory: ./docusaurus-cms
              run: pnpm run typecheck

            - name: Format check
              working-directory: ./docusaurus-cms
              run: pnpm run format:check

            # - name: Lint
            #   run: pnpm run lint

            - name: Run tests
              working-directory: ./docusaurus-cms
              run: pnpm run test

            # - name: Build
            #   working-directory: ./docusaurus-cms
            #   run: pnpm run build
